version: "3"

services:
  battle-test-app:
    build:
      context: .
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring": {
        "data": {
          "mongodb": {
            "uri": "mongodb://db:27017",
            "database": "alfa-battle"
          }
        }
      },
      "server": {
        "port": 8090
      },
      "coefficient": 80,
      "mapping": {
        "taskPorts": {
          "0": 8090,
          "1": 8080,
          "2": 8081
        },
        "taskNames": {
          "0": "com.soypita.battle.testcases.ShowcaseTest",
          "1": "com.soypita.battle.testcases.Task1Test",
          "2": "com.soypita.battle.testcases.Task2Test"
        }
      }
    }'
    ports:
      - 8090:8090
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"