version: "3"

services:
  battle-test-app:
    image: arpmipg/alfa-battle-private:battle-test-api
    volumes:
      - ./log:/log/testapp/
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring": {
        "data": {
          "mongodb": {
            "uri": "mongodb://db:27017",
            "database": "alfa-battle"
          }
        }
      },
      "server": {
        "port": 8080
      },
      "coefficient": 80,
      "mapping": {
        "taskPorts": {
          "0": 8080,
          "1": 8080,
          "2": 8081,
          "4": 8083
        },
        "taskNames": {
          "0": "com.soypita.battle.testcases.ShowcaseTest",
          "1": "com.soypita.battle.testcases.Task1Test",
          "2": "com.soypita.battle.testcases.Task2Test",
          "4": "com.soypita.battle.testcases.Task4Test"
        }
      }
    }'
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
