version: "3"

services:
  battle-test-app:
    image: arpmipg/alfa-battle-private:battle-test-api_0.1.1
    volumes:
      - ./log:/log/testapp/
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring": {
        "data": {
          "mongodb": {
            "uri": "mongodb://84.201.128.80:27017,84.201.129.66:27017,84.201.135.153:27017/alfa-battle?replicaSet=rs0",
            "database": "alfa-battle"
          }
        }
      }
    }'
    ports:
      - 8080:8080
