server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding:           true
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: alfa-battle
  kafka:
    streams:
      application-id:                           payment-analytics-api
      client-id:                                payment-analytics-api
      bootstrap-servers:                        localhost:29092
      properties:
        metrics.recording.level:                DEBUG
        processing.guarantee:                   at_least_once
        auto.offset.reset:                      earliest
        cache.max.bytes.buffering:              10240
        commit.interval.ms:                     60000
        default:
          deserialization.exception.handler:  org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
        consumer:
          group-id:                             payment-analytic-consumer
          max.poll.records:                     30

management:
  endpoints:
    web:
      base-path: /admin

analytics:
  kafka:
    enabled:                                    true
    sources:
      rawPaymentSource:                    RAW_PAYMENTS
