spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: alfa-battle

server:
  port: 8090

coefficient: 80

mapping:
  taskPorts:
    0: 8090
    1: 8080
  taskNames:
    0: com.soypita.battle.testcases.ShowcaseTest
    1: com.soypita.battle.testcases.Task1Test
