spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: alfa-battle

server:
  port: 8080

coefficient: 80

mapping:
  taskPorts:
    1: 8080
    2: 8081
    4: 8083
    5: 8084
  taskNames:
    1: com.soypita.battle.testcases.Task1Test
    2: com.soypita.battle.testcases.Task2Test
    4: com.soypita.battle.testcases.Task4Test
    5: com.soypita.battle.testcases.Task5Test
